#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_buffer_reference_uvec2 : require
layout(local_size_x = 1) in;
layout(buffer_reference, std430, buffer_reference_align = 4) readonly buffer Input { uint value[]; };
layout(set = 0, binding = 0, std430) buffer Output { uint value; } output_data;
layout(push_constant) uniform Address { uvec2 address; } pc;
void main()
{
   output_data.value = Input(pc.address).value[3];
}
