#version 450

layout(local_size_x = 1) in;
layout(push_constant) uniform Push { uint word[64]; } pc;
layout(set = 0, binding = 0) buffer Data { uint value[]; } data[32];

uint signature()
{
   return pc.word[0] ^ pc.word[31] ^ pc.word[47] ^ pc.word[62] ^ pc.word[63];
}

void main()
{
   uint base = pc.word[2] * 4;
   data[0].value[base] = signature();
   data[0].value[base + 1] = data[1].value[0];
   data[0].value[base + 2] = data[31].value[0];
}
